### ISSUE TITLE
USERSTORY # 1: Gather General Requirements & Visual Layout

### ISSUE THREAD

**Issue by roc-11** [roc-11/pp4-jetset-journal#14]
EPIC: #1 

As a **Developer** I can **see how the site should be laid out and make a detailed plan** so that **the site functionality can be developed in an incremental manner**.

## Acceptance Criteria
* I (the developer), will understand exactly what the goals of the site/project are.
* I (the developer), will have a clear visual plan of the site's front-end and plan the user journey/stories.
* I (the developer), will understand the relationship between the database models.

## Tasks
- [x] Set up the project Kanban Board
- [x] Write general requirements document
- [x] Create wireframes for the front-end layout
- [x] Create the database (DB) schema/DB structure
- [x] Create a flow chart/logic chart
- [x] Research Bootstrap templates
- [x] Create the site logo
- [x] Decide on a colour scheme
- [x] Choose font styles
- [x] Gather graphics, icons and images
- [x] Write content for pages

Story Points: 1

**Comment by roc-11** [comment]
Bootstap Template: Clean Blog 
[(https://startbootstrap.com/previews/clean-blog-jekyll)](url)

Colour Scheme for Blog: #4ABDAC (Fresh - Green Shade), #FC4A1A (Vermillion - Warm Orange Shade), #F7B733 (Sunshine - Warm Yellow Shade), #DFDCE3 (Clean - White/Grey Base Shade)
<img width="738" alt="Screenshot 2024-02-14 at 12 15 35" src="https://github.com/roc-11/pp4-jetset-journal/assets/137648972/0bfc627a-42ca-466c-83e8-5557f1b60363">
Inspired by post on Canva [https://www.canva.com/learn/website-color-schemes/](url)

Hero Image for Homepage 
[https://www.pexels.com/photo/woman-and-man-riding-on-motorcycle-2174656/](url) by Ajay Donga on Pexels (free to use). Edit and personalise using Photoshop. 

Jetset Journal Logo - Deisgned using Canva (template: Black and White Monogram Business Logo)
![1](https://github.com/roc-11/pp4-jetset-journal/assets/137648972/53ede7eb-14b4-4f5a-a573-8d94ae6a4453)

Font 
Body - Roboto [https://fonts.google.com/specimen/Roboto](url)
Headings - Nunito [https://fonts.google.com/specimen/Nunito](url)
