### ISSUE TITLE
USERSTORY #2: Initial Django project setup

### ISSUE THREAD

**Issue by roc-11** [roc-11/pp4-jetset-journal#15]
EPIC: #2 

As a **developer** I can **set up the initial project files in the developer environment and deploy to Heroku** so that **I have a base for my project and can resolve any deployment issues early on**.

## Acceptance Criteria
* I (the developer), will use Gitpod to create a new Django project, using the Code Institute Gitpod template.
* I (the developer), will create an Agile Kanban Board to manage my project. This will include epics, user story templates, acceptance criteria and tasks.
* I (the developer), will label each item on the Project Board utilising the MoSCoW prioritisation approach.
* I (the developer), will deploy a basic initial version of my Django Project to Heroku, ensuring my secret keys and environment variables remain hidden from the public. 

## Tasks
- [x] Create a Github Repo, using the CI template
- [x] Create Github Project Board 
- [x] Create issues templates
- [x] Add epics and user story items to Kanban board and prioritise into Sprints
- [x] Edit the template ReadMe file and add an empty ReadMe Project Template, with main headings
- [x] Create pp4 Django project
- [x] Create SQL Database
- [x] Create secret keys
- [x] Add env.py and add necessary items to .gitignore file
- [x] Create Heroku project
- [x] Deploy initial project
- [x] Fix any deployment bugs, if present
