### ISSUE TITLE
USERSTORY # 3: Create Front-End Site, using Bootstrap Template

### ISSUE THREAD

**Issue by roc-11** [roc-11/pp4-jetset-journal#16]
EPIC: #3 

As a **Developer** I can **design and deploy a basic website** so that **it meets the minimum viable requirements**.

## Acceptance Criteria
* I (the developer), will develop the basic Django front-end website, using Bootstrap, to create the main structure of the site. 
* I (the developer), will use the project wireframes will be used to guide the front-end development. 
* As a site user, I will be able to navigate to each page of the website clearly and click all buttons/links, bringing me to the expected page.

## Tasks
- [x] Create Base.html
- [x] Create Site Header
- [x] Create Site Footer
- [x] Create Site Navbar
- [x] Create Home Page
- [x] Create About Page
- [x] Create Contact Page
- [x] Create Post Detail Page
- [x] Create Account Login Page
- [x] Create Account Register Page
- [x] Add favicon

Story Points = 2
