### ISSUE TITLE
USERSTORY #4: Create Post Model for Blog

### ISSUE THREAD

**Issue by roc-11** [roc-11/pp4-jetset-journal#17]
EPIC: #4 

As a **site admin** I can **create, read, update and delete blog posts in the admin section** so that **I can manage my blog content**.

## Acceptance Criteria
* A a logged in site admin, I can create a blog post
* A a logged in site admin, I can save a draft blog post and finish it at a later time
* A a logged in site admin, I can read a blog post
* A a logged in site admin, I can update a blog post
* A a logged in site admin, I can delete a blog post
* As a front-end site user, I can see all the blog posts appear on the front end
* Given more than one post in the database, these multiple posts are listed
* Then the user sees all post titles with pagination to choose what to read

## Tasks
- [x] Create Blog app
- [x] Create Blog (post) model and database fields
- [x] Create Blog details template
- [x] Migrate database
- [x] Create URL pattern and add URL path to project URL
- [x] Register post model in admin.py
- [x] Create Comment Model and Database Fields
- [x] Register Comment model  in admin.py
- [x] Create view methods
- [x] Link to template
- [x] Connect to urls.py
- [x] Update HTML template
- [x] Create static files
- [x] Implement pagination to display all posts

Story Points = 4
