### ISSUE TITLE
USERSTORY #6: Create SuperUser Account

### ISSUE THREAD

**Issue by roc-11** [roc-11/pp4-jetset-journal#19]
EPIC: #5 

As a **Site Admin** I can **login into the Admin area** so that **I can manage website content**.

## Acceptance Criteria
* As an admin, I can log in to the back end of Django.
* As an admin, I will see database table fields with accessible links.
* As an admin, I can create, edit delete and make a blog post for the front-end.
* As an admin, I can create a draft post or publish a post for the website.
* As an admin, I can approve comments.
* As an admin, I manage contact requests.

## Tasks
- [x] Create superuser
- [x] Register first database models in admin
- [x] Create filter methods and functions
- [x] Check that blog posts can be managed via Django admin section.
- [x] Check that comments can be managed via Django admin section.
- [x] Check that contact requests can be managed via Django admin section.
