### ISSUE TITLE
USERSTORY #7: Customise admin area

### ISSUE THREAD

**Issue by roc-11** [roc-11/pp4-jetset-journal#20]
EPIC: #5 

As a **Site Admin** I can **recognise the admin area has the same look & feel as the front-end site** so that **website continuity is maintained**.

## Acceptance Criteria
* As site admin, I will see the company logo in the top left.
* As site admin, I will see familiar colours instead of the default Django colours in the admin area.

## Tasks
- [x] Install Summernote Package - rich text editor on back-end/DB 
- [x] Replace Django Admin with company logo
- [x] Change the default colors to match the front-end templates

Story Points = 0.5
