### ISSUE TITLE
USERSTORY #8: User Registration

### ISSUE THREAD

**Issue by roc-11** [roc-11/pp4-jetset-journal#21]
EPIC: #5 

As a **Site User** I can **login, logout and register** so that **I can view my user profile and comment on blog posts**.

## Acceptance Criteria
* As a site user, when I click on register it brings me to a registration form.
* As a site user, when I click on login, it brings me to a login form.
* As a site user, when I click on logout it logs me out and redirects me to the home page

## Tasks
- [x] Create accounts app
- [x] Create views
- [x] Write register function
- [x] Write login function
- [x] Write logout function
- [x] Write dashboard function
- [x] Add URL patterns
- [x] Link to templates
- [x] Ensure functions implement defensive programming
- [x] Ensure all user forms are validated 

Story Points = 2
