### ISSUE TITLE
USERSTORY #9: Create Comment Model

### ISSUE THREAD

**Issue by roc-11** [roc-11/pp4-jetset-journal#22]
EPIC: #6

As a **Site Admin** I can **create Comments table/model** so that **I can manage comments**.

## Acceptance Criteria
* As site admin, I can log in to the Django admin area and create a new comment.

## Tasks
- [x] Create Comment model in Blog app
- [x] Create database fields for Comment
- [x] Migrate database
- [x] Register model in admin.py
- [x] Add some Comment data to test

Story Points = 1
