### ISSUE TITLE
USERSTORY #10: View Comments and Comment on a post

### ISSUE THREAD

**Issue by roc-11** [roc-11/pp4-jetset-journal#23]
EPIC: #6 

As a **Site User/Admin** I can **view comments on an individual post** so that **I can read the conversation**.

## Acceptance Criteria
* Given one or more user comments the admin can view them
* Then a site user can click on the comment thread to read the conversation

## Tasks
- [x] Link the back-end comment model to the front-end
- [x] Add code to template so comments appear under a particular blog post
- [x] Create text area for a logged in user to comment on a post

Story Points = 1
