### ISSUE TITLE
USERSTORY #11: Modify or delete Comment on a Post

### ISSUE THREAD

**Issue by roc-11** [roc-11/pp4-jetset-journal#24]
EPIC: #6 

As a **Site User** I can **modify or delete my comment on a post** so that **I can be involved in the conversation**.

## Acceptance Criteria
* Given a logged in site user, they can modify their comment.
* Given a logged in user, they can delete their comment

## Tasks
- [x] Create Edit Button and Delete Button
- [x] Link edit button to edit comment template
- [x] Prepopulate comment text field when edit button clicked (with DB data)
- [x] Update Comment button submits changes to DB
- [x] Status reverts to pending (approved by Site Admin)
- [x] Link Delete Button to Bootstrap Modal - defensive programming
- [x] "Are you sure you want to delete?" modal appears before user can delete comment
- [x] Delete button then removes DB comment

Story Points = 2
