### ISSUE TITLE
USERSTORY #13: Create Destination Model

### ISSUE THREAD

**Issue by roc-11** [roc-11/pp4-jetset-journal#26]
EPIC: #7 

As a **Site Admin** I can **create Destination table/model** so that **I can manage destinations and enable filtering by Destination on the front-end**.

## Acceptance Criteria
* As site admin, I can log in to the Django admin area and create a Destination.
* Destination is a foreign key to Post Table, so each Post should have a corresponding Desination.

## Tasks
- [ ] Create Destination app
- [ ] Create Destination model 
- [ ] Create database fields for Destination
- [ ] Update Post Model with Destination field (FK)
- [ ] Migrate database
- [ ] Register model in admin.py
- [ ] Add some Destination data to test
- [ ] Create Destinations Search Filters Results Page (Front-End)

Story Points = 1
