### ISSUE TITLE
USERSTORY #15: Request for contact

### ISSUE THREAD

**Issue by roc-11** [roc-11/pp4-jetset-journal#28]
EPIC: #8 

As a **Potential Collaborator** I can **fill in a contact form** so that **I can submit a request for contact**.

## Acceptance Criteria
* Potential collaborator can fill in a contact form to request collaboration.

## Tasks
- [x] Link contact to crispy form
- [x] Import crispy form
- [x] Create forms.py
- [x] Submit Button to submit form to the Database

Story Points = 2
