### ISSUE TITLE
USERSTORY #18: Read about the site

### ISSUE THREAD

**Issue by roc-11** [roc-11/pp4-jetset-journal#32]
EPIC: #9 

As a **Site User** I can **click on the About link** so that **I can read about the site**.

## Acceptance Criteria
* As a site user, when the About link is clicked, the about text is visible

## Tasks
- [x] Create the About app
- [x] Create the About Model, register model & migrate
- [x] Create the Views (function)
- [x] Create the About HTML template
- [x] Create About URLs and link it to the main project in settings/URLs

Story Points = 1
