### ISSUE TITLE
USERSTORY #19: Add and update the about text

### ISSUE THREAD

**Issue by roc-11** [roc-11/pp4-jetset-journal#33]
EPIC: #9 

As a **Site Admin** I can **create or update the about page content** so that **it is available on the site**.

## Acceptance Criteria
* As a site admin, the About app is visible in the admin panel.
* As a site admin, I can edit the about page content from the admin panel.

## Tasks
- [x] Use Summernote in About Model for rich-text editor in Django Admin
- [x] Check that the About content can be edited from the Admin page
- [x] Register for Cloudinary and install it
- [x] Host About images on Cloudinary
- [x] Build front end layout for about page

Story Points = 2
