### ISSUE TITLE
USERSTORY #20: Create Like Model

### ISSUE THREAD

**Issue by roc-11** [roc-11/pp4-jetset-journal#35]
EPIC: #34 

As a **Site Admin** I can **create Like table/model** so that **I can manage likes**.

## Acceptance Criteria
* As site admin, I can log in to the Django admin area and view likes on a post/edit like status.

## Tasks
- [x] Create Like model in Blog app
- [x] Create database fields for Like
- [x] Migrate database
- [x] Register model in admin.py
- [x] Add some like data to test

Story Points = 1
