### ISSUE TITLE
USERSTORY #21: View Likes and Like/Unlike a post

### ISSUE THREAD

**Issue by roc-11** [roc-11/pp4-jetset-journal#36]
EPIC: #34 

As a **Site User/Admin** I can **view likes on an individual post** so that **I can be an active member of Jetset Journal/react to a blog post**.

## Acceptance Criteria
* Given a post, the admin can view the number of likes on that post
* Then a site user can can also view the number of likes on a post
* As a logged in site user, I can like / unlike a post

## Tasks
- [x] Link the back-end like model to the front-end
- [x] Add code to template so likes appear under a particular blog post
- [x] Create a like button
- [x] User can click the like button to like/unlike a post (if logged in)
- [x] Likes are disabled for unregistered users

Story Points = 1
