### ISSUE TITLE
USERSTORY #22: Create User Profile/Dashboard Page

### ISSUE THREAD

**Issue by roc-11** [roc-11/pp4-jetset-journal#38]
EPIC:  #37 

As a **Logged in User** I can **view my user profile** so that **manage my profile and update my user details**.

## Acceptance Criteria
* As a user, I will need to log in to access the dashboard
* As a user, once I have logged in I will see a "My Profile" tab on the navigation bar
* As a user, I can view my username, profile picture and about me details

## Tasks
- [x] Create UserProfile Model
- [x] Register UserProfile in Admin.py
- [x] Create MyProfile view 
- [x] Create view method
- [x] Create the My Profile HTML template
- [x] Create URL pattern
- [x] Add URL path to project URL
- [x] Create / Link to template
- [x] Connect to urls.py
- [x] Display user data 

Story Points = 1
