### ISSUE TITLE
USERSTORY #23: Edit User Profile/Dashboard Page

### ISSUE THREAD

**Issue by roc-11** [roc-11/pp4-jetset-journal#39]
EPIC:  #37 

As a **Logged in User** I can **edit my user profile** so that **manage my profile and update my user details**.

## Acceptance Criteria
* As a user, I can click the edit button to edit my user details
* As a user, the update profile button will update the database and reload my user profile

## Tasks
- [x] Create Edit Button and add to My Profile
- [x] Create form elements for user to update profile on front end
- [x] Form will be prepopulated with User info prior to edit
- [x] Update Profile button submits changes to db and Profile

Story Points = 2
