### ISSUE TITLE
Fix Issues for project re-submission

### ISSUE THREAD

**Issue by roc-11** [roc-11/pp4-jetset-journal#43]
EPIC: 

As a **developer** I can **fix bugs and issues with the website** so that **I can pass PP4 upon project resubmission**.

## Acceptance Criteria
* As a site user, I can receive a verification email upon account registration.
* As a site user, I can view my user profile/dashboard and edit my personal information from this page.
* As a site user, I can favourite a blog post and return to it at a later time/date.
* As a site admin, I can add a new blog post from the front-end using a UI form.
* As a site admin, I can edit and delete blog post from the front-end using a UI form/button.

## Tasks
- [x] Set up a Gamil account for Jetset Journal and create an app password.
- [x] Edit the settings.py file and config vars on Heroku to ensure email is set up correctly for the site.
- [x] Remove the UserProfile model from the blog app. Migrate the changes.
- [x] Create UserProfile app, model, urls, templates and views (use receiver so Profile created for each User).
- [x] Style the UserProfile page.
- [x] Add wishlist/favourites functionality for users to favourite a blog post.
- [x] Add form, template and view so admins can add a blog post on front-end.
- [x] Add functionality for admins to edit or delete a blog post on the front-end.
