### ISSUE TITLE
Documentation: finish README file

### ISSUE THREAD

**Issue by roc-11** [roc-11/pp4-jetset-journal#45]
Update README.md file to include changes and improvements made for project resubmission:

## Tasks
- [x] Edit User Stores
- [x] Features - add email
- [x] Features - wishlist/favourites
- [x] Features - admin add/edit/delete blog post
- [x] Features - user profile/dashboard
- [x] Credits - leonardo.ai to change hero image
- [x] Move old bugs on Features from submission 1 to TESTING.md file
