### ISSUE TITLE
Documentation: finish TESTING file

### ISSUE THREAD

**Issue by roc-11** [roc-11/pp4-jetset-journal#46]
Update TESTING.md file to include changes and improvements made for project resubmission:

## Tasks
- [x] Update python and html validation tool screenshots.
- [x] Add bug fixes to the fixes section: User Profile, image previews, Hero image slow css.
- [x] Bug fix: dropped table (blog_userprofile) and couldn't migrate - explain. 
- [x] Manual Testing: include new user stories and testing of new/enhanced features.
- [x] Manual Testing: include new admin features.
- [x] Test all the features of the website. 
- [x] Run automatic python tests.
