### ISSUE TITLE
Project Resubmission

### ISSUE THREAD

**Issue by roc-11** [roc-11/pp4-jetset-journal#47]
Resubmit PP4 for grading

## Tasks
- [x] Development config var removed Heroku
- [x] Remove Development from env.py
- [x] **Secret keys hidden** N.B.
- [x] Readme.md file updated
- [x] Testing.md file updated
- [x] Manual check of all features to ensure they are working correctly
- [x] Submit PP4
